#version: '3.8'

#definindo containers
services:
  db: #banco de dados
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"


  #backend
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    
    volumes:
      - ./backend:/app
    #environment:
    #  - DATABASE_URL=postgresql://admin:admin@db/auth_db
    env_file:
      - .env
    depends_on:
      - db

  #frontend
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    
    volumes:
      - ./frontend:/app
      - /app/node_modules


volumes:
  postgres_data:
